### ISSUE TITLE
Blank page with : Contact your administrator to obtain your 2FA secret.

### ISSUE THREAD

**Issue by pinkfloydFR** [itemir/apache_2fa#15]
Hi,

French guy, apache 2.4, ubuntu 18.04 

After installing all, web site ask me for login and password then show me only a white page with :

Contact your administrator to obtain your 2FA secret.

What i am doing wrong ? Thanks !

`

<VirtualHost *:1443>
     ServerName denis.xxx.com

     RewriteEngine On
     RewriteCond %{REQUEST_URI} !^/auth/
     RewriteCond %{HTTP_COOKIE} !^.*2FA_Auth=([a-zA-Z0-9]+)
     RewriteRule ^(.*)$ /auth/auth?$1?%{QUERY_STRING} [L,R=302]

     RewriteCond %{REQUEST_URI} !^/auth/
     RewriteCond %{HTTP_COOKIE} ^.*2FA_Auth=([a-zA-Z0-9]+)
     RewriteCond /etc/apache2/2fa/apache_2fa/state/%1 !-f
     RewriteRule ^(.*)$ /auth/auth?$1?%{QUERY_STRING} [L,R=302]

     ScriptAlias /auth/ /etc/apache2/2fa/apache_2fa/

     <Directory /etc/apache2/2fa/apache_2fa>
       AuthType Digest
       AuthName "denis.xxx.com"
       AuthDigestDomain /
       AuthDigestProvider file
       AuthUserFile /etc/apache2/2fa/apache_2fa/apache_credentials
       Require valid-user
     </Directory>

     <Directory /var/www/html/android>
       AuthType Digest
       AuthName "denis.xxx.com"
       AuthDigestDomain /
       AuthDigestProvider file
       AuthUserFile /etc/apache2/2fa/apache_2fa/apache_credentials
       Require valid-user
     </Directory>

     Include ssl.conf

</VirtualHost>

`

**Comment by itemir** [comment]
```
if user is None or user_secret is None:
    print("Content-type: text/html\r\n\r\n")
    print("Contact your administrator to obtain your 2FA secret.\n")
    sys.exit()
```

This happens i the HTTP authentication is not configured correctly or the username that is used for HTTP authentication does not match what is provided in the tokens file. 

Make sure you get an HTTP auth prompt before you get to 2FA page and make sure the user you use in that authentication popup is also in tokens.json file. Also make sure the permissions are right so that Apache can read tokens.json file.
