### ISSUE TITLE
apache_2fa generates different token than Google Authenticator

### ISSUE THREAD

**Issue by phwes** [itemir/apache_2fa#16]
When implementing this solution I am not able to gain access to the protected page.

By printing the generated token on the auth page I was able to see that the token is not the same as google authenticator generates on my phone. 

I have checked the file for the secret key and they are the same.

**Comment by itemir** [comment]
That is odd. I don't have a good answer for this other then (re-)verifying the token. Can you please retry it by removing and re-adding to Google Authenticator? If it doesn't work, try the same with Authy (another app that uses the same algorithm).

**Comment by phwes** [comment]
Yes, I realized that my VM had not synced it's time. My fault. Tried to post this and close the issue but for some reason github did not allow me.

Great application, thank you!
