### ISSUE TITLE
Looks like token is accepted, but i'm redirected to auth page again and again

### ISSUE THREAD

**Issue by zaharcelac** [itemir/apache_2fa#2]
Thank you for your Authenticator code.
It almost works for me... but I'm stuck at page asking me token...
Can't understand what I did wrong.

My setup: ubuntu server 17.04 with default apache setup (with default index.html page i'm trying to protect)
Website page located at: **/var/www/html/**
Your code was cloned to: **/var/www/a2fa/**

I added lines listed below to my **/etc/apache2/sites-available/000-default.conf**:

```
RewriteEngine On

RewriteCond %{REQUEST_URI} !^/auth/
RewriteCond %{HTTP_COOKIE} !^.*2FA_Auth=([a-zA-Z0-9]+)
RewriteRule ^(.*)$ /auth/auth?$1?%{QUERY_STRING} [L,R=302]

RewriteCond %{REQUEST_URI} !^/auth/
RewriteCond %{HTTP_COOKIE} ^.*2FA_Auth=([a-zA-Z0-9]+)
RewriteCond /var/www/a2fa/state/%1 !-f
RewriteRule ^(.*)$ /auth/auth?$1?%{QUERY_STRING} [L,R=302]

ScriptAlias /auth/ /var/www/a2fa/

<Directory /var/www/a2fa>
     AuthType Digest
     AuthName "yourdomain.com"
     AuthDigestDomain /
     AuthDigestProvider file
     AuthUserFile /var/www/a2fa/apache_credentials
     Require valid-user
</Directory>
 
<Directory /var/www/html>
     AuthType Digest
     AuthName "yourdomain.com"
     AuthDigestDomain /
     AuthDigestProvider file
     AuthUserFile /var/www/a2fa/apache_credentials
     Require valid-user
</Directory>
```

I can pass apache digest authentication. But OTP token is not accepted, and google auth page is shown again and again.
I can see that cookie files appear in **/var/www/a2fa/state** folder, so it means that token is valid... but it seems that apache rewrite rules fail somewhere.
Could you please advise.

**Comment by itemir** [comment]
When you get redirected to the auth cgi script, what does the full URL look like on the browser, can you paste it here?

**Comment by zaharcelac** [comment]
It is always like this: `http://10.11.11.101/auth/auth?/%3f`

**Comment by itemir** [comment]
You are using http. This type of security would really only make sense when using https but I guess you know this.

With http, cookie may not be visible to the browser, depending on the browser you use. Try commenting out/removing these two lines in auth code:

      cookie['2FA_Auth']['secure'] = True
      cookie['2FA_Auth']['httponly'] = True

See if that makes a difference. That being said, you should really consider using https, even with a self signed certificate.

**Comment by zaharcelac** [comment]
That's right! Works on SSL (for testing purposes I wanted to save some minutes disregarding SSL configuration, and started testing your code on plain HTTP).
Thank you!

**Comment by itemir** [comment]
Cool, glad to hear it. I will clarify the documentation so people don't get confused.

**Comment by itemir** [comment]
BTW, if you benefit from the code and instructions, please star the repository. It helps others to find it more easily when they need it.

**Comment by vlafranca** [comment]
Hi @itemir ,
I reopen this issue because I am currently facing the same problem with https enabled.
I tryed without and with https but I keep seeing the google authenticator form ... any idea ?
