### ISSUE TITLE
Internal Server Error with LDAP

### ISSUE THREAD

**Issue by jskyfacts** [itemir/apache_2fa#20]
I am trying to use the 2fa with LDAP authentication. I have referred to the guide here https://www.hallam.ch/blog/index.php/2020/01/13/apache-and-two-factor-authentication-2fa-using-ldap-accounts/
I have setup everything properly but after entering my ldap credentials I get internal server error.

**Comment by itemir** [comment]
When you get an internal server error, you should have the details of that that in your error logs. See what the underlying issue is from those logs.

**Comment by jskyfacts** [comment]
> When you get an internal server error, you should have the details of that that in your error logs. See what the underlying issue is from those logs.

![image](https://user-images.githubusercontent.com/55120792/85368869-ab55fa00-b549-11ea-8338-91be2d1799d1.png)
I checked the logs but can't find anything there.

**Comment by itemir** [comment]
What file is this? You need to find the apache error log file, not the syslog or global system messages (/var/messages).

Start here: https://www.google.com/search?q=apache+error+log+location

**Comment by jskyfacts** [comment]
Sorry for not being clear. It is the apache error log from /var/log/apache2/ location.

**Comment by itemir** [comment]
It is very hard to help without having specifics. Apache must be logging the details of that internal server error somewhere. Unless you can find it, there is no way to guess what the issue might be.

**Comment by jskyfacts** [comment]
The REMOTE_USER in auth file is always empty even after successful authentication with LDAP. 
![image](https://user-images.githubusercontent.com/55120792/85651541-f268fa00-b6c5-11ea-94ba-4452b345e51a.png)
I can see the user in apache logs but the script cannot access it. What do you think I might be doing wrong? 
I apologize for bothering with silly things but I am novice trying to make this work.

**Comment by itemir** [comment]
Why do you think the script cannot access it? I don't see anything in the logs that indicates that.

Looks like you are following the instructions [from this page](https://www.hallam.ch/blog/index.php/2020/01/13/apache-and-two-factor-authentication-2fa-using-ldap-accounts/), try asking your question there or simplify your configuration to make the base case work as outlined in the documentation without LDAP first and proceed step by step.

**Comment by itemir** [comment]
I will close this, please re-open if you have specifics.
