### ISSUE TITLE
You don't have permission to access /auth/auth on this server.

### ISSUE THREAD

**Issue by jonathanmmm** [itemir/apache_2fa#4]
Hi,

Thank You for this great package.

I am stuck and can't access my website anymore.

My apache2.conf looks like this:

<<Directory />
        Options -Indexes
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/html/private_website/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

My Virtual Host looks like:

<IfModule mod_ssl.c>
    <VirtualHost _default_:1111>
        ServerAdmin admin@localhost
        ServerName mywebsite.com
        ServerAlias mywebsite.com
        DocumentRoot /var/www/html/private_website/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/apache.crt
        SSLCertificateKeyFile /etc/apache2/ssl/apache.key
        SSLCompression off
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /var/www/html>
         SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" \
                        nokeepalive ssl-unclean-shutdown \
                        downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

RewriteEngine On

RewriteCond %{REQUEST_URI} !^/auth/
RewriteCond %{HTTP_COOKIE} !^.*2FA_Auth=([a-zA-Z0-9]+)
RewriteRule ^(.*)$ /auth/auth?$1?%{QUERY_STRING} [L,R=302]

RewriteCond %{REQUEST_URI} !^/auth/
RewriteCond %{HTTP_COOKIE} ^.*2FA_Auth=([a-zA-Z0-9]+)
RewriteCond </home/pi/apache_2fa>/state/%1 !-f
RewriteRule ^(.*)$ /auth/auth?$1?%{QUERY_STRING} [L,R=302]

ScriptAlias /auth/ </home/pi/apache_2fa>/

<Directory </home/pi/apache_2fa/>>
    AuthType Digest
    AuthName "mywebsite.com"
    AuthDigestDomain /
    AuthDigestProvider file
    AuthUserFile </home/pi/apache_2fa>/apache_credentials
    Require valid-user
</Directory>

<Directory </var/www/html/private_website/>>
    AuthType Digest
    AuthName "mywebsite.com"
    AuthDigestDomain /
    AuthDigestProvider file
    AuthUserFile </home/pi/apache_2fa>/apache_credentials
    Require valid-user

</Directory>
    </VirtualHost>
</IfModule>

I get the error 403 Forbidden.

before all worked fine with ssl certificate etc.

The file I access is the index.html file

I type into the browser:

https://mywebsite.com:1111/private_website/

and the rewrite creates: https://mywebsite.com:1111/auth/auth?/private_website/%3f

Website and the folder name are changed, but illustrate the same issue.

I hope you can help me :)

**Comment by itemir** [comment]
Looks like you wrapped the directories around < and >, you should remove them.

</home/pi/apache_2fa> should be /home/pi/apache_2fa
</var/www/html/private_website/> should be /var/www/html/private_website/

Change all instances and see if the problem persists. If so, look at the apache error log and see what it gives as the reason of 403.

**Comment by jonathanmmm** [comment]
Great, thankyou it worked for me :)

I am not that experienced with the whole linux/debian universe.

Now I have the problem, that I can pass the authentication and also the 2FA but it says:

Not Found

The requested URL /private_website/ was not found on this server.

I tried it also with .../private_website/index.html (which is my website index) and it shows

Not Found

The requested URL /private_website/index.html was not found on this server.



And the guide for creating my own google authenticator key, I only need the beginning of it, right?

Is your private key that you have posted gone, if I put my own in the token.json file?

**Comment by itemir** [comment]
If you can pass authentication, you should consult to the Apache configuration for the rest. Make sure that the directory exists, and look at the error logs for any hints.

You should remove the ample secret in the tokens.json file and also clean the apache_credentials file, then you should be good for removing the test_user, only your users will stay.
