### ISSUE TITLE
Proxy instead of Directory (Question)

### ISSUE THREAD

**Issue by bertjanssens93** [itemir/apache_2fa#7]
Hi Itemir,

I have no experienced background in Apache and Virtual Hosts, but I would like to implement the following.  I have one amazon server instance (linux) with a running Jenkins on 'localhost:8080'. I want the user to use Multifactor authentication on Port 80, and provide the user access to Jenkins via the Proxy after authentication.
Regretfully it is not possible to set up a Proxy using the Directory block, or I at least don't know how. Do you see a possibility to use your code in combination with a Proxy?

Kind Regards,
Bert

**Comment by itemir** [comment]
This solution will not work with a proxy.
