### ISSUE TITLE
use active directory instead of htaccess 

### ISSUE THREAD

**Issue by adambarnett52** [itemir/apache_2fa#9]
hi

Is it possible to use active directory for user auth and then the 2fa ?

Thanks

**Comment by ghost** [comment]
Yes really easy even :


        <Directory /var/www/html/apache_2fa>
               AuthLDAPBindDN "LDAPBINDUSER"
               AuthLDAPBindPassword "PASSWORD"
               AuthLDAPURL "ldap://192.168.1.1/dc=server,dc=local?sAMAccountName?sub?(objectClass=*)"
               AuthType Basic
               AuthName "Please use your AD account"
               AuthBasicProvider ldap
               AuthUserFile /dev/null
               Require valid-user
        </Directory>

        <Directory /var/www/html>
               AuthLDAPBindDN "LDAPBINDUSER"
               AuthLDAPBindPassword "PASSWORD"
               AuthLDAPURL "ldap://192.168.1.1/dc=server,dc=local?sAMAccountName?sub?(objectClass=*)"
               AuthType Basic
               AuthName "Please use your AFD account"
               AuthBasicProvider ldap
               AuthUserFile /dev/null
               Require valid-user
        </Directory>

**Comment by adambarnett52** [comment]
Hi

Yup. After some trial and error I got it working. 

Thanks

**Comment by itemir** [comment]
Thanks @emeriss, closing this one.

**Comment by jskyfacts** [comment]
> Hi Yup. After some trial and error I got it working. Thanks
> […](#)
> On 21 May 2019, at 12:27, Emeriss ***@***.***> wrote: Yes really easy even : <Directory /var/www/html/apache_2fa> AuthLDAPBindDN "LDAPBINDUSER" AuthLDAPBindPassword "PASSWORD" AuthLDAPURL "ldap://192.168.1.1/dc=server,dc=local?sAMAccountName?sub?(objectClass=*)" AuthType Basic AuthName "Please use your AD account" AuthBasicProvider ldap AuthUserFile /dev/null Require valid-user </Directory> <Directory /var/www/html> AuthLDAPBindDN "LDAPBINDUSER" AuthLDAPBindPassword "PASSWORD" AuthLDAPURL "ldap://192.168.1.1/dc=server,dc=local?sAMAccountName?sub?(objectClass=*)" AuthType Basic AuthName "Please use your AFD account" AuthBasicProvider ldap AuthUserFile /dev/null Require valid-user </Directory> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hey @adambarnett52, how did you get it to work? I am still facing issues. It just keeps giving 500 internal error

**Comment by adambarnett52** [comment]
Hi

I got this when i was missing some of the python libraries. Check out the apache logs and try running the 2fa python code manually to see if it complains about musings libs

**Comment by jskyfacts** [comment]
> Hi I got this when i was missing some of the python libraries. Check out the apache logs and try running the 2fa python code manually to see if it complains about musings libs
> […](#)
> Sent from my iPhone
> On 23 Jun 2020, at 06:43, pllvpipalwa ***@***.***> wrote: ﻿ Hi Yup. After some trial and error I got it working. Thanks … On 21 May 2019, at 12:27, Emeriss @.*> wrote: Yes really easy even : <Directory /var/www/html/apache_2fa> AuthLDAPBindDN "LDAPBINDUSER" AuthLDAPBindPassword "PASSWORD" AuthLDAPURL "ldap://192.168.1.1/dc=server,dc=local?sAMAccountName?sub?(objectClass=)" AuthType Basic AuthName "Please use your AD account" AuthBasicProvider ldap AuthUserFile /dev/null Require valid-user <Directory /var/www/html> AuthLDAPBindDN "LDAPBINDUSER" AuthLDAPBindPassword "PASSWORD" AuthLDAPURL "ldap://192.168.1.1/dc=server,dc=local?sAMAccountName?sub?(objectClass=)" AuthType Basic AuthName "Please use your AFD account" AuthBasicProvider ldap AuthUserFile /dev/null Require valid-user — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. Hey @adambarnett52, how did you get it to work? I am still facing issues. It just keeps giving 500 internal error — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I already tried that.. there are no errors when i run the python code. I am following this guide https://www.hallam.ch/blog/index.php/2020/01/13/apache-and-two-factor-authentication-2fa-using-ldap-accounts/ to achieve it. And from what I see it is not redirecting to /auth once I enter my credentials and gives 500 internal error . Any idea why? rewrite module is enabled and is also turned on.

**Comment by adambarnett52** [comment]
you will need to share your config
